# Generated by Django 5.2 on 2025-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_apiapp', '0002_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
